export default {
  printWidth: 120,
  semi: false,
  singleQuote: true,
  arrowParens: 'always',
  trailingComma: 'es5',
  endOfLine: 'auto',
  tabWidth: 2,
  importOrder: [
    '^react',
    '^[a-z]',
    '^@?\\w',
    '^@/utils',
    '^@/hooks',
    '^@/components',
    '^\\u0000',
    '^\\.\\.(?!/?$)',
    '^\\.\\./?$',
    '^\\./(?=.*/)(?!/?$)',
    '^\\.(?!/?$)',
    '^\\./?$',
    '^.+\\.?(scss)$',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: [import('@trivago/prettier-plugin-sort-imports')],
}
